"""
Django settings for ne project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from dotenv.main import dotenv_values
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

config = dotenv_values(BASE_DIR / '.env')

if 'BASE_RW_DIR' in config:
    BASE_RW_DIR = Path(config['BASE_RW_DIR'])
    if not os.path.exists(BASE_RW_DIR):
        os.makedirs(BASE_RW_DIR)
else:
    BASE_RW_DIR = BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config['DEBUG']

ALLOWED_HOSTS = ['*']

# BASE_URL_DJANGO for Django and Heimdall 
BASE_URL_DJANGO = config['BASE_URL_DJANGO']
BASE_URL_PDU = config['BASE_URL_PDU']

# Trusted Origins for CSRF
CSRF_TRUSTED_ORIGINS = [
    BASE_URL_DJANGO,
    BASE_URL_PDU
]

CORS_ORIGIN_ALLOW_ALL = True

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'app',
]

REST_FRAMEWORK = {

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
        # 'rest_framework.permissions.IsAuthenticated',
        # 'utils.permissions.IsAuthorized'
        # 'rest_framework.permissions.IsAdminUser',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    # 'DEFAULT_PAGINATION_CLASS': 'rest.paginations.Custom20Pagination',
    # 'PAGE_SIZE': 20
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ne.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ne.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_RW_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Languages
LANGUAGE_ES = 'es'
LANGUAGE_EN = 'en'

LANGUAGES = (
    (LANGUAGE_ES, _('Spanish')),
    (LANGUAGE_EN, _('English')),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)


# STATIC_URL = "https://%s.s3.amazonaws.com/" % S3_BUCKET
STATIC_URL = '/static/'
STATIC_ROOT = ''
STATICFILES_DIRS = ((BASE_DIR / 'static'), )


# MEDIA FILES
MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = os.path.join('/', 'home', 'root', '.ne', 'uploads')


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# url for login
LOGIN_URL = '/login'

# Superuser
SUPERUSER_USERNAME = config['SUPERUSER_USERNAME']
SUPERUSER_EMAIL = config['SUPERUSER_EMAIL']
SUPERUSER_FIRST_NAME = config['SUPERUSER_FIRST_NAME']
SUPERUSER_LAST_NAME = config['SUPERUSER_LAST_NAME']
SUPERUSER_PASSWORD = config['SUPERUSER_PASSWORD']

# MAX NUMBER OF PARAMETER THAT MAY BE RECEIVED VIA GET OR POST
DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000

# MAX MEMORY SIZE TO DATA UPLOAD IN DJANGO ADMIN (BY DEFAULT=2621440 -> 2.5 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 20971520
