# Generated by Django 4.1.5 on 2023-01-13 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_datetime', models.DateTimeField()),
                ('input_active_power_total', models.FloatField(default=0)),
                ('input_reactive_power_total', models.FloatField(default=0)),
                ('input_apparent_power_total', models.FloatField(default=0)),
                ('input_energy_total', models.FloatField(default=0)),
                ('input_current_total', models.FloatField(default=0)),
                ('input_voltage_avg', models.FloatField(default=0)),
                ('output_active_power_total', models.FloatField(default=0)),
                ('output_reactive_power_total', models.FloatField(default=0)),
                ('output_apparent_power_total', models.FloatField(default=0)),
                ('output_energy_total', models.FloatField(default=0)),
                ('output_current_total', models.FloatField(default=0)),
                ('output_voltage_avg', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Data Summary',
                'db_table': 'data_summary',
                'ordering': ('-data_datetime',),
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Hosts',
                'db_table': 'hosts',
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.PositiveSmallIntegerField(unique=True)),
                ('low_limit', models.FloatField(blank=True, null=True)),
                ('high_limit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Inputs',
                'db_table': 'inputs',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('socket_type', models.CharField(blank=True, max_length=100, null=True)),
                ('low_limit', models.FloatField(blank=True, null=True)),
                ('high_limit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Outputs',
                'db_table': 'outputs',
            },
        ),
        migrations.CreateModel(
            name='DataOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField(default=0)),
                ('phase_total', models.FloatField(default=0)),
                ('phase_vi', models.FloatField(default=0)),
                ('active_power', models.FloatField(default=0)),
                ('reactive_power', models.FloatField(default=0)),
                ('apparent_power', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('voltage', models.FloatField(default=0)),
                ('current', models.FloatField(default=0)),
                ('power_factor', models.FloatField(default=0)),
                ('data_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.datasummary')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.output')),
            ],
            options={
                'verbose_name_plural': 'Data Outputs',
                'db_table': 'data_outputs',
            },
        ),
        migrations.CreateModel(
            name='DataInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField(default=0)),
                ('phase_total', models.FloatField(default=0)),
                ('phase_vi', models.FloatField(default=0)),
                ('active_power', models.FloatField(default=0)),
                ('reactive_power', models.FloatField(default=0)),
                ('apparent_power', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('voltage', models.FloatField(default=0)),
                ('current', models.FloatField(default=0)),
                ('power_factor', models.FloatField(default=0)),
                ('data_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.datasummary')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.input')),
            ],
            options={
                'verbose_name_plural': 'Data Inputs',
                'db_table': 'data_inputs',
            },
        ),
    ]
