# Generated by Django 4.1.5 on 2023-02-11 01:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_battery_value', models.FloatField(default=0)),
                ('last_data_received', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sensors',
                'db_table': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='DataSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_datetime', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature (ºC)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Humidity (%)')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Pressure (pa)')),
                ('rssi', models.IntegerField(blank=True, null=True, verbose_name='Rssi (dB)')),
                ('battery', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sensor')),
            ],
            options={
                'verbose_name_plural': 'Data Sensor',
                'db_table': 'data_sensors',
                'unique_together': {('data_datetime', 'sensor')},
            },
        ),
    ]
