# Generated by Django 4.1.5 on 2023-02-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sensor_datasensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
