# Generated by Django 4.1.5 on 2023-02-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sensor_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_battery_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
