# Generated by Django 4.1.5 on 2024-01-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sensor_last_battery_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datainput',
            options={'verbose_name_plural': 'Data - Inputs'},
        ),
        migrations.AlterModelOptions(
            name='dataoutput',
            options={'verbose_name_plural': 'Data - Outputs'},
        ),
        migrations.AlterModelOptions(
            name='datasensor',
            options={'verbose_name_plural': 'Data - Sensors'},
        ),
    ]
