# Generated by Django 4.1.5 on 2024-01-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_datainput_options_alter_dataoutput_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datainput',
            options={'verbose_name_plural': 'Datos - Entradas'},
        ),
        migrations.AlterModelOptions(
            name='dataoutput',
            options={'verbose_name_plural': 'Datos - Salidas'},
        ),
        migrations.AlterModelOptions(
            name='datasensor',
            options={'verbose_name_plural': 'Datos - Sensores'},
        ),
        migrations.AlterModelOptions(
            name='datasummary',
            options={'ordering': ('-data_datetime',), 'verbose_name_plural': 'Datos - Resumen'},
        ),
        migrations.AlterModelOptions(
            name='output',
            options={'verbose_name_plural': 'Salidas'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name_plural': 'Sensores'},
        ),
    ]
