# Generated by Django 4.1.5 on 2024-01-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_datainput_options_alter_dataoutput_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasensor',
            name='humidity',
            field=models.FloatField(blank=True, null=True, verbose_name='Humedad (%)'),
        ),
        migrations.AlterField(
            model_name='datasensor',
            name='pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión (pa)'),
        ),
        migrations.AlterField(
            model_name='datasensor',
            name='temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura (ºC)'),
        ),
    ]
